# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          stef
subtitle:       blog
paginate:       5
baseurl:        "/"
url:            "https://stefkim.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         stef
  url:          https://stefkim.github.io
  email:        stefkim@aol.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
